services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $extension: '@Zikula\ScribiteModule\ZikulaScribiteModule'

    Zikula\ScribiteModule\:
        resource: '../../*'
        exclude: '../../{Editor/*/vendor,Resources/doc}'

    Zikula\ScribiteModule\Helper\:
        resource: '../../Helper/*'
        lazy: true
