/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('fullpage',{
	title : 'Propriedades do Documento',
	desc : 'Propriedades do Documento',
	meta_tab : 'Geral',
	appearance_tab : 'Apar&ecirc;ncia',
	advanced_tab : 'Avan&ccedil;ado',
	meta_props : 'Informa&ccedil;&atilde;o Meta',
	langprops : 'Codifica&ccedil;&atilde;o e Idioma',
	meta_title : 'T&iacute;tulo',
	meta_keywords : 'Palavras',
	meta_description : 'Descri&ccedil;&atilde;o',
	meta_robots : 'Robos',
	doctypes : 'Tipo de Documento',
	langcode : 'C&oacute;digo do Idioma',
	langdir : 'Dire&ccedil;&atilde;o do Idioma',
	ltr : 'Esquerda para direita',
	rtl : 'Direita para esquerda',
	xml_pi : 'Declara&ccedil;&atilde;o XML',
	encoding : 'Codifica&ccedil;&atilde;o de Caracteres',
	appearance_bgprops : 'Propriedades do Fundo',
	appearance_marginprops : 'Margens do Corpo',
	appearance_linkprops : 'Cores dos Links',
	appearance_textprops : 'Propriedades do Texto',
	bgcolor : 'C&ocirc;r do Fundo',
	bgimage : 'Fundo da imagem',
	left_margin : 'Margem Esquerda',
	right_margin : 'Margem Direita',
	top_margin : 'Margem Superior',
	bottom_margin : 'Margem Inferior',
	text_color : 'C&ocirc;r do Texto',
	font_size : 'Tamanho da Fonte',
	font_face : 'Tipo de Fonte',
	link_color : 'C&ocirc;r do link',
	hover_color : 'C&ocirc;r do mouse sobre',
	visited_color : 'C&ocirc;r do link visitado',
	active_color : 'C&ocirc;r do link ativo',
	textcolor : 'C&ocirc;r',
	fontsize : 'Tamanho da Fonte',
	fontface : 'Tipo de Fonte',
	meta_index_follow : 'Indexar e seguir os links',
	meta_index_nofollow : 'Indexar e n&atilde;o seguir os links',
	meta_noindex_follow : 'N&atilde;o indexar mas seguir os links',
	meta_noindex_nofollow : 'N&atilde;o indexar e n&atilde;o seguir os links',
	appearance_style : 'Folha de Estilo e propriedades dos estilos',
	stylesheet : 'Folha de Estilo',
	style : 'Estilo',
	author : 'Autor',
	copyright : 'Copyright',
	add : 'Adicionar novo elemento',
	remove : 'Remover elemento selecionado',
	moveup : 'Mover selecionado para cima',
	movedown : 'Mover selecionado para baixo',
	head_elements : 'Elementos do Head',
	info : 'Informa&ccedil;&atilde;o',
	info_text : '',
	add_title : 'Elemento T&iacute;tulo',
	add_meta : 'Elemento Meta',
	add_script : 'Elemento Script',
	add_style : 'Elemento Estilo',
	add_link : 'Elemento Link',
	add_base : 'Elemento Base',
	add_comment : 'Coment&aacute;rio',
	title_element : 'T&iacute;tulo',
	script_element : 'Script',
	style_element : 'Estilo',
	base_element : 'Base',
	link_element : 'Link',
	meta_element : 'Meta',
	comment_element : 'Coment&aacute;rio',
	src : 'Src',
	language : 'Idioma',
	href : 'Href',
	target : 'Destino',
	rel : 'Rel',
	type : 'Tipo',
	charset : 'Charset',
	defer : 'Defer',
	media : 'Midia',
	properties : 'Properties',
	name : 'Nome',
	value : 'Valor',
	content : 'Conte&uacute;do',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Geral',
	advanced_props : 'Avan&ccedil;ado',
	delta_width : 0,
	delta_height : 0
});
