/**
 * pt_br lang variables
 * Brazilian Portuguese
 *
 * Author
 * Revision and modifications:
 *           Marcio Barbosa (mpg) <mpg@mpg.com.br>
 * First Release : November 20, 2006 - TinyMCE Version : 2.0.8
 */
tinyMCE.addToLang('style',{
title : 'Editar folha de estilo CSS',
styleinfo_desc : 'Editar Estilo CSS',
apply : 'Aplicar',
text_tab : 'Texto',
background_tab : 'Fundo',
block_tab : 'Bloco',
box_tab : 'Caixa',
border_tab : 'Borda',
list_tab : 'Lista',
positioning_tab : 'Posicionamento',
text_props : 'Texto',
text_font : 'Fonte',
text_size : 'Tamanho',
text_weight : 'Largura',
text_style : 'Estilo',
text_variant : 'Varia&ccedil;&atilde;o',
text_lineheight : 'Altura da Linha',
text_case : 'Caso',
text_color : 'C&ocirc;r',
text_decoration : 'Decora&ccedil;&atilde;o',
text_overline : 'Dobrescrito',
text_underline : 'Subscrito',
text_striketrough : 'Tachado',
text_blink : 'Piscante',
text_none : 'nenhum',
background_color : 'C&ocirc;r do fundo',
background_image : 'Fundo da imagem',
background_repeat : 'Repetir',
background_attachment : 'Anexo',
background_hpos : 'Posi&ccedil;&atilde;o horizontal',
background_vpos : 'Posi&ccedil;&atilde;o Vertical',
block_wordspacing : 'Espa&ccedil;amento de Palavras',
block_letterspacing : 'Espa&ccedil;aento de Letras',
block_vertical_alignment : 'Alinnhamento Vertical',
block_text_align : 'Alinhamento do texto',
block_text_indent : 'Identa&ccedil;&atilde;o do texto',
block_whitespace : 'Espa&ccedil;os em branco',
block_display : 'Visualiza&ccedil;&atilde;o',
box_width : 'Largura',
box_height : 'Altura',
box_float : 'Flutuante',
box_clear : 'Limpar',
padding : 'Espa&ccedil;amento',
same : 'Igual para todos',
top : 'Superior',
right : 'Direita',
bottom : 'Inforio',
left : 'Esquerda',
margin : 'Margem',
style : 'Estilo',
width : 'Largura',
height : 'Altura',
color : 'C&ocirc;r',
list_type : 'Tipo',
bullet_image : 'Imagem tipo Bullet',
position : 'Posicionamento',
positioning_type : 'Tipo',
visibility : 'Visibilidade',
zindex : 'Z-index',
overflow : 'Sobrescrever',
placement : 'Localiza&ccedil;&atilde;o',
clip : 'Clip'
});
