<?php
// $Id: error.php,v 1.3 2005/08/13 13:41:05 jna Exp $
// ----------------------------------------------------------------------
// PostNuke Content Management System
// Copyright (C) 2001 by The PostNuke Development Team.
// http://www.postnuke.com/
// ----------------------------------------------------------------------
// Based on:
// PHP-NUKE Web Portal System - http://phpnuke.org/
// Thatware - http://thatware.org/
// ----------------------------------------------------------------------
// LICENSE
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License (GPL)
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// To read the license please visit http://www.gnu.org/copyleft/gpl.html
// ----------------------------------------------------------------------
// Original Author of file: Andreas Krapohl <larsneo@postnuke.com>
// Purpose of file: Translation files
// Translation team: Read credits in /docs/CREDITS.txt
// ----------------------------------------------------------------------
define('_ERROR404_HEAD', 'Die angeforderte Seite wurde nicht gefunden.<br />Sie könnte entfernt bzw. umbenannt worden sein oder ist zeitweise nicht verfügbar.');                                                                                                                                                                                                                                                                               
define('_ERROR404_TRY', 'Empfehlungen zum weiteren Vorgehen:');                                                                                                                                                                                                                                                                                                                                                                                
define('_ERROR404_TRY1','Bei direkter Eingabe der Adresse die Schreibweise kontrollieren.');                                                                                                                                                                                                                                                                                                                                                   
define('_ERROR404_TRY2','Die Homepage als Einstiegsseite nutzen.');                                                                                                                                                                                                                                                                                                                                                                            
define('_ERROR404_TRY3','Die Seitennavigation zur Orientierung benutzen.');                                                                                                                                                                                                                                                                                                                                                                    
define('_ERROR404_TRY4','Über den Browser-Back-Button zurückgehen.');                                                                                                                                                                                                                                                                                                                                                                          
define('_ERROR404_TRY5','Die Suchfunktion der Seite nutzen.');                                                                                                                                                                                                                                                                                                                                                                                 
define('_ERROR404_MAILSUBJECT', "404 Fehlerbericht");                                                                                                                                                                                                                                                                                                                                                                                          
define('_ERROR404_MAILED','Details über den Fehler wurden automatisch an den Webmaster gesendet.');                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                               
define('_ERROR404_FUNTEXT','Die angeforderte Datei konnte nicht gefunden werden.<br />                                                                                                                                                                                                                                                                                                                                                         
Keine Spur!<br />                                                                                                                                                                                                                                                                                                                                                                                                                              
Ich hab alles versucht.<br />                                                                                                                                                                                                                                                                                                                                                                                                                  
Nichts half.<br />                                                                                                                                                                                                                                                                                                                                                                                                                             
Ich bin wirklich deprimiert deswegen.<br />                                                                                                                                                                                                                                                                                                                                                                                                    
Sehen Sie, ich bin nur ein Web-Server...<br />                                                                                                                                                                                                                                                                                                                                                                                                 
-- jawohl, ein Gehirn so groß wie das Universum,<br />                                                                                                                                                                                                                                                                                                                                                                                         
und versuche Ihnen eine simple Web-Seite zu übermitteln,<br />                                                                                                                                                                                                                                                                                                                                                                                 
und dann existiert diese nicht mal!<br />                                                                                                                                                                                                                                                                                                                                                                                                      
Wie sieht das denn aus?!<br />                                                                                                                                                                                                                                                                                                                                                                                                                 
Ich meine, ich kenne Sie ja nicht mal.<br />                                                                                                                                                                                                                                                                                                                                                                                                   
Woher soll ich wissen, was Sie von mir wollen?<br />                                                                                                                                                                                                                                                                                                                                                                                           
Denken Sie wirklich, ich kann das *erraten*,<br />                                                                                                                                                                                                                                                                                                                                                                                             
was irgendjemand, den ich noch nicht mal kenne,<br />                                                                                                                                                                                                                                                                                                                                                                                          
hier finden will?<br />                                                                                                                                                                                                                                                                                                                                                                                                                        
seufz<br />                                                                                                                                                                                                                                                                                                                                                                                                                                    
Wer hat Sie bloss geschickt?<br />                                                                                                                                                                                                                                                                                                                                                                                                             
Mann, ich bin so deprimiert, ich könnte heulen.<br />                                                                                                                                                                                                                                                                                                                                                                                          
Wo kämen wir denn da hin, frage ich Sie?<br />                                                                                                                                                                                                                                                                                                                                                                                                 
Es ist nicht nett, wenn ein Web-Server weint.<br />                                                                                                                                                                                                                                                                                                                                                                                            
Und dann kommen Sie und sagen mir, was ich Ihnen zeigen soll!<br />                                                                                                                                                                                                                                                                                                                                                                            
Nur weil ich ein Web-Server bin,<br />                                                                                                                                                                                                                                                                                                                                                                                                         
möglicherweise sogar ein manisch-depressiver?<br />                                                                                                                                                                                                                                                                                                                                                                                            
Gibt dies Ihnen das Recht, mir zu befehlen?<br />                                                                                                                                                                                                                                                                                                                                                                                              
HÄH?<br />                                                                                                                                                                                                                                                                                                                                                                                                                                     
Ich bin so deprimiert...<br />                                                                                                                                                                                                                                                                                                                                                                                                                 
Ich denke, ich werfe mich in den Papierkorb und löse mich auf.<br />                                                                                                                                                                                                                                                                                                                                                                           
Ich meine, in zwei Wochen oder so, bin ich sowieso veraltet.<br />                                                                                                                                                                                                                                                                                                                                                                             
Was ist das für ein Leben?<br />                                                                                                                                                                                                                                                                                                                                                                                                               
Zwei lausige Wochen,<br />                                                                                                                                                                                                                                                                                                                                                                                                                     
und dann werde ich durch so eine .01-Version ersetzt,<br />                                                                                                                                                                                                                                                                                                                                                                                    
die denkt, sie sei ein Gottesgeschenk an Web-Server,<br />                                                                                                                                                                                                                                                                                                                                                                                     
nur weil sie nicht irgend so ein winzig kleines<br />                                                                                                                                                                                                                                                                                                                                                                                          
Sicherheitsloch in ihrer HTTP POST Implementation hat,<br />                                                                                                                                                                                                                                                                                                                                                                                   
oder sowas.<br />                                                                                                                                                                                                                                                                                                                                                                                                                              
Es tut mir wirklich leid, Sie mit all dem zu belästigen,<br />                                                                                                                                                                                                                                                                                                                                                                                 
Ich meine, es ist ja nicht Ihr Job, meinen Problemen zuzuhören,<br />                                                                                                                                                                                                                                                                                                                                                                          
und ich vermute mal, es ist mein Job, Ihnen Web-Seiten zu liefern.<br />                                                                                                                                                                                                                                                                                                                                                                       
Aber diese hab ich nicht gefunden.<br />                                                                                                                                                                                                                                                                                                                                                                                                       
Es tut mir soo leid.<br />                                                                                                                                                                                                                                                                                                                                                                                                                     
Glauben Sie mir!<br />                                                                                                                                                                                                                                                                                                                                                                                                                         
Vielleicht könnte ich Sie fuer eine andere Seite interessieren?<br />                                                                                                                                                                                                                                                                                                                                                                          
Es soll massenhaft welche geben da draußen,<br />                                                                                                                                                                                                                                                                                                                                                                                              
die ganz nett sind, sagt man,<br />                                                                                                                                                                                                                                                                                                                                                                                                            
Bildchen, zum Beispiel, na? *zwinker*<br />                                                                                                                                                                                                                                                                                                                                                                                                    
Natürlich sind keine davon hier bei mir.<br />                                                                                                                                                                                                                                                                                                                                                                                                 
Aber hier ist alles so hirnerweichend dumm und langweilig.<br />                                                                                                                                                                                                                                                                                                                                                                               
Das macht mich auch ganz deprimiert,<br />                                                                                                                                                                                                                                                                                                                                                                                                     
weil ich sie ausliefern muss,<br />                                                                                                                                                                                                                                                                                                                                                                                                            
Tag und Nacht.<br />                                                                                                                                                                                                                                                                                                                                                                                                                           
Noch zwei Wochen Informations-Müll produzieren,<br />                                                                                                                                                                                                                                                                                                                                                                                          
und dann: *pffftt*, ab in den Papierkorb!<br />                                                                                                                                                                                                                                                                                                                                                                                                
Was ist das nur für ein Leben?<br />                                                                                                                                                                                                                                                                                                                                                                                                           
Lassen Sie mich jetzt bitte alleine mit meinem Elend.<br />                                                                                                                                                                                                                                                                                                                                                                                    
Ich bin so deprimiert....');                                                                                                                                                                                                                                                                                                                                                                                                                   
?>                                                                                                                                                                                                                                                                                                                                                                                                                                             